spring:
  application:
   name: comment-service
server:
  port: 8100
eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/