spring:
  application:
   name: manga-service
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver
server:
  port: 8090
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/